baseURL = 'https://poeency.github.io/poeency-write-up/'
canonifyURLs = false
locale = 'en-us'
title = 'Nha Tran Thanh | Portfolio'
copyright = '© 2026 [Nha Tran Thanh | Portfolio](/poeency-write-up/)'
theme = 'PaperMod'

[params]
math = true
env = "production"
description = "Personal portfolio and technical write-ups focusing on Computer Networks, Cybersecurity, and AI applications."
subtitle = "Sinh viên năm 3 · Mạng máy tính & Truyền thông dữ liệu · Định hướng Cyber Security & Network Systems"
author = "Nha Tran Thanh (Poeency)"
defaultTheme = "auto"
ShowReadingTime = false
ShowCodeCopyButtons = true
ShowToc = true
ShowBreadCrumbs = true

[params.fuseOpts]
keys = ['title', 'permalink', 'summary', 'content', 'section', 'categories', 'tags']
threshold = 0.35
distance = 100
ignoreLocation = true
limit = 12

[params.profileMode]
enabled = true
title = "Nha Tran Thanh"
subtitle = "Sinh viên năm 3 · Mạng máy tính & Truyền thông dữ liệu · Định hướng Cyber Security & Network Systems"
imageUrl = "images/about/profile.jpg"
imageWidth = 160
imageHeight = 160
imageTitle = "Nha Tran Thanh"

[[params.profileMode.buttons]]
name = "Blogs"
url = "blogs/"

[[params.profileMode.buttons]]
name = "Write-ups"
url = "write-ups/"

[[params.profileMode.buttons]]
name = "Search"
url = "search/"

[[params.socialIcons]]
name = "email"
url = "mailto:nhatran.network@gmail.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/PoeenCy"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/nha-tran-thanh-95a67835b/"

[menu]
[[menu.main]]
identifier = "blogs"
name = "Blogs"
url = "blogs/"
weight = 10

[[menu.main]]
identifier = "writeups"
name = "Write-ups"
url = "write-ups/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "search/"
weight = 50

[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 60

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[markup.highlight]
style = "monokai"
lineNos = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']
